### ISSUE TITLE
Links on main page are not clickable

### ISSUE THREAD

**Issue by aberres** [clarklab/chowdown#10]
Might not be relevant with the code from the beta release, mentioning it nevertheless:

All links below `For the home chef` and `For the developer` are not clickable (neither is the text selectable) with a desktop browser.

In the small mobile view everything is fine. Things are also working when tweaking the CSS to use the mobile special case.

Problematic snippet:

```css
.bg-blue-tile{background: #007FFF url(../assets/tile.png); position:relative;}
@media all and (min-width:40em){
.bg-blue-tile:after{position:absolute; top:0; left:0; right:0; bottom:0; content:" "; box-shadow:inset 0 0 100px 20px #007FFF; z-index:1;}
}
```
